# A sample Gemfile
source 'https://rubygems.org'
gem 'appium_capybara', '~> 1.4', '>= 1.4.1'
gem 'appium_lib', '~> 9.8', '>= 9.8.3'
gem 'appium_lib_core', '~> 1.2', '>= 1.2.6'
gem 'appium_thor', '~> 1.0', '>= 1.0.1'
gem 'byebug'
gem 'capybara'
gem 'capybara-email'
gem 'capybara-screenshot'
gem 'capybara_table'
gem 'cucumber', '~> 2.4.0'
gem 'dotenv', '~> 2.1.1'
gem 'ffaker'
gem 'headless'
gem 'nokogiri', '~> 1.8.2'
gem 'parallel_tests'
gem 'pry'
gem 'pry-byebug'
gem 'rails', '~> 5.1', '>= 5.1.5'
gem 'recursive-open-struct'
gem 'report_builder'
gem 'rest-client'
gem 'rspec'
gem 'rubocop', '~> 0.46', require: false
gem 'selenium-webdriver'
gem 'site_prism'
gem 'syntax'
gem 'test-unit', '~> 3.2', '>= 3.2.7'
gem 'touch_action', '~> 1.3', '>= 1.3.3'
